[build]
  publish = "build"  # or the directory where your build output is located
  command = "npm run build"  # or your build command, e.g., "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
