[build]
  command = "npm run build"  # or your build command, e.g., "yarn build"
  publish = "build"  # or the directory where your build output is located
  base = "/"  # Corrected this line

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
