[build]
  command = "npm run build"
  publish = "dist"  # Update this to match your build output directory
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
